openapi: 3.1.0
info:
  title: Notion Task API
  version: "1.0.0"
servers:
  - url: https://notion-task-api.<your-subdomain>.workers.dev
paths:
  /:
    get:
      summary: Get all tasks from Notion DB
      operationId: getTasks
      responses:
        '200':
          description: A list of tasks from Notion
          content:
            application/json:
              schema:
                type: object
                additionalProperties: true
