openapi: 3.1.0
info:
  title: Notion Task API
  version: "1.0.0"
paths:
  /:
    get:
      summary: Get all tasks from Notion DB
      operationId: getTasks
      responses:
        '200':
          description: A list of tasks from Notion
          content:
            application/json:
              schema:
                type: object
                properties:
                  results:
                    type: array
                    description: Notion API の `results` 配列
                    items:
                      type: object
                      description: Notion のデータベースアイテムのオブジェクト
                required:
                  - results
servers:
  - url: https://notion-task-api.even-raining.workers.dev
